# src/diagnostics.py

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from itertools import combinations

from .config import BASE_DIR, TARGET_COL
from .metrics import mse, qlike

# -------------------- Paths --------------------
FORECAST_INPUT_DIR = BASE_DIR / "forecasts"  # Original forecasts generated by models
FORECAST_ALIGNED_DIR = BASE_DIR / "results" / "forecasts"
EVAL_DIR = BASE_DIR / "results" / "evaluation"
PLOT_DIR = BASE_DIR / "results" / "plots"
DATA_PATH = BASE_DIR / "data" / "processed" / "SP500_processed.csv"

# Ensure directories exist
FORECAST_ALIGNED_DIR.mkdir(parents=True, exist_ok=True)
EVAL_DIR.mkdir(parents=True, exist_ok=True)
PLOT_DIR.mkdir(parents=True, exist_ok=True)


# -------------------- Helpers --------------------
def load_forecast_csv(path: Path) -> pd.DataFrame:
    """
    Load a forecast CSV and standardize column names.
    Keeps only Date + first forecast column.
    Ensures y_pred is always 1D.
    """
    df = pd.read_csv(path)
    df["Date"] = pd.to_datetime(df["Date"])

    # Keep only Date + first non-Date column
    forecast_col = [c for c in df.columns if c != "Date"][0]
    df = df[["Date", forecast_col]]
    df = df.rename(columns={forecast_col: "y_pred"})

    # Flatten y_pred in case it's 2D
    df["y_pred"] = df["y_pred"].values.ravel()

    return df


def align_with_truth(forecast_df: pd.DataFrame, y_true: pd.Series) -> pd.DataFrame:
    """
    Align forecast with true target values by Date.
    Keeps only Date, y_true, y_pred columns.
    """
    df = forecast_df.copy()
    df["y_true"] = y_true.loc[df["Date"]].values
    df = df[["Date", "y_true", "y_pred"]]
    return df.dropna()


# -------------------- Main evaluation --------------------
def evaluate_all_forecasts():
    """
    Evaluate all forecasts:
    - Save aligned forecasts CSVs in results/forecasts/
    - Save pairwise model comparisons in results/evaluation/
    - Save a single plot comparing baseline vs all other models in results/plots/
    - Print metrics (MSE & QLIKE) for all models
    """
    # Load true data
    true_df = pd.read_csv(DATA_PATH)
    true_df["Date"] = pd.to_datetime(true_df["Date"])
    true_df = true_df.set_index("Date")
    y_true = true_df[TARGET_COL]

    # Load and align forecasts
    model_dfs = {}
    for file in FORECAST_INPUT_DIR.glob("*.csv"):
        model = file.stem
        fcst = load_forecast_csv(file)
        aligned = align_with_truth(fcst, y_true)

        # Save aligned forecast CSV
        aligned.to_csv(FORECAST_ALIGNED_DIR / f"{model}_aligned.csv", index=False)

        model_dfs[model] = aligned

    # -------------------- Pairwise evaluation --------------------
    for model_a, model_b in combinations(model_dfs.keys(), 2):
        df_a = model_dfs[model_a]
        df_b = model_dfs[model_b]

        comparison = pd.DataFrame({
            "Model": [model_a, model_b],
            "MSE": [
                mse(df_a["y_true"].values, df_a["y_pred"].values.ravel()),
                mse(df_b["y_true"].values, df_b["y_pred"].values.ravel()),
            ],
            "QLIKE": [
                qlike(df_a["y_true"].values, df_a["y_pred"].values.ravel()),
                qlike(df_b["y_true"].values, df_b["y_pred"].values.ravel()),
            ],
        })

        comparison.to_csv(
            EVAL_DIR / f"{model_a}_vs_{model_b}.csv",
            index=False
        )

    # -------------------- Print metrics --------------------
    print("\n=== Model Metrics ===")
    metrics_summary = []
    for model, df in model_dfs.items():
        m = mse(df["y_true"].values, df["y_pred"].values.ravel())
        q = qlike(df["y_true"].values, df["y_pred"].values.ravel())
        metrics_summary.append({"Model": model, "MSE": m, "QLIKE": q})

        print(f"{model}: MSE = {m:.6e}, QLIKE = {q:.6e}")

    metrics_df = pd.DataFrame(metrics_summary)
    metrics_df.to_csv(EVAL_DIR / "all_models_metrics.csv", index=False)

    # -------------------- Single combined plot: baseline vs all models --------------------
    if "baselines" in model_dfs:
        base_df = model_dfs["baselines"]
        plt.figure(figsize=(14, 7))

        # Plot baseline
        plt.plot(base_df["Date"], base_df["y_pred"], label="Baseline", linewidth=2)

        # Plot all other models
        for model, df in model_dfs.items():
            if model == "baselines":
                continue
            plt.plot(df["Date"], df["y_pred"], label=model, alpha=0.8)

        # Plot true values
        plt.plot(
            base_df["Date"],
            base_df["y_true"],
            color="black",
            linestyle="--",
            label="True"
        )

        plt.title("Baseline vs All Model Forecasts")
        plt.xlabel("Date")
        plt.ylabel("Volatility")
        plt.legend()
        plt.tight_layout()
        plt.savefig(PLOT_DIR / "baseline_vs_all_models.png")
        plt.show()

    print("\n✔ Diagnostics completed successfully.")